### ISSUE TITLE
Error after docker image install

### ISSUE THREAD

**Issue by Stuke00** [SpaceinvaderOne/Macinabox#31]
BigSur-install.img not downloading.

Traceback (most recent call last):
File "fetch-macos2.py", line 501, in <module>
sys.exit(main())
File "fetch-macos2.py", line 497, in main
action_download(args)
File "fetch-macos2.py", line 236, in action_download
info = get_image_info(session, bid=args.board_id, mlb=args.mlb,
File "fetch-macos2.py", line 147, in get_image_info
headers, output = run_query(url, headers, post)
File "fetch-macos2.py", line 80, in run_query
response = urlopen(req)
File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib/python3.8/urllib/request.py", line 531, in open
response = meth(req, response)
File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
response = self.parent.error(

File "/usr/lib/python3.8/urllib/request.py", line 569, in error

return self._call_chain(*args)
File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
result = func(*args)
File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 417: Expectation Failed

chmod: /isos/BigSur-install.img: No such file or directory
rm: can't remove '/Macinabox/tools/FetchMacOS/BaseSystem/*': No such file or directory

**Comment by theklutzysamurai** [comment]
Same thing happened to me. I had to change my VM location. I believe it happens when your VM directory is corrupt. I could not manually create a new folder in the VM directory (/mnt/user/domains/) until I changed the VM disk setting to not use the Cache and run Mover.
