### ISSUE TITLE
i hava some unexpected err, but i dont understand why

### ISSUE THREAD

**Issue by orangejx** [SpaceinvaderOne/Macinabox#42]
dear developer, this is log of docker
```
ErrorWarningSystemArrayLogin


[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing...
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing...
[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing...
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-logmonitor-states.sh: executing...
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing...
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
[cont-init.d] 00-set-app-deps.sh: executing...
[cont-init.d] 00-set-app-deps.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing...
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing...
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 00-xdg-runtime-dir.sh: executing...
[cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
[cont-init.d] 10-certs.sh: executing...
[cont-init.d] 10-certs.sh: exited 0.
[cont-init.d] 10-cjk-font.sh: executing...
[cont-init.d] 10-cjk-font.sh: exited 0.
[cont-init.d] 10-nginx.sh: executing...
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing...
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing...
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] 20-machineid_fix.sh: executing...
[cont-init.d] 20-machineid_fix.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] starting s6-fdholderd...
[services.d] starting certsmonitor...
[services.d] starting nginx...
[services.d] starting xvfb...
[nginx] starting...
[certsmonitor] disabling service: secure connection not enabled.
[xvfb] starting...
[services.d] starting logmonitor...
[services.d] starting statusmonitor...
[logmonitor] no file to monitor: disabling service...
[services.d] starting openbox...
[statusmonitor] no file to monitor: disabling service...
[openbox] starting...
[services.d] starting x11vnc...
[services.d] starting app...
[x11vnc] starting...
[app] starting Macinabox with VirtManager...
[services.d] done.
12/04/2021 01:57:48 passing arg to libvncserver: -rfbport
12/04/2021 01:57:48 passing arg to libvncserver: 5900
12/04/2021 01:57:48 passing arg to libvncserver: -rfbportv6
12/04/2021 01:57:48 passing arg to libvncserver: -1
12/04/2021 01:57:48 passing arg to libvncserver: -httpportv6
12/04/2021 01:57:48 passing arg to libvncserver: -1
12/04/2021 01:57:48 passing arg to libvncserver: -desktop
12/04/2021 01:57:48 passing arg to libvncserver: Macinabox with VirtManager
12/04/2021 01:57:48 x11vnc version: 0.9.14 lastmod: 2015-11-14 pid: 815

12/04/2021 01:57:48 Using X display :0
12/04/2021 01:57:48 rootwin: 0x43 reswin: 0x400001 dpy: 0x7f914b20
12/04/2021 01:57:48
12/04/2021 01:57:48 ------------------ USEFUL INFORMATION ------------------
12/04/2021 01:57:48 X DAMAGE available on display, using it for polling hints.
12/04/2021 01:57:48 To disable this behavior use: '-noxdamage'
12/04/2021 01:57:48
12/04/2021 01:57:48 Most compositing window managers like 'compiz' or 'beryl'
12/04/2021 01:57:48 cause X DAMAGE to fail, and so you may not see any screen
12/04/2021 01:57:48 updates via VNC. Either disable 'compiz' (recommended) or
12/04/2021 01:57:48 supply the x11vnc '-noxdamage' command line option.
12/04/2021 01:57:48 X COMPOSITE available on display, using it for window polling.
12/04/2021 01:57:48 To disable this behavior use: '-noxcomposite'
12/04/2021 01:57:48
12/04/2021 01:57:48 Wireframing: -wireframe mode is in effect for window moves.
12/04/2021 01:57:48 If this yields undesired behavior (poor response, painting
12/04/2021 01:57:48 errors, etc) it may be disabled:
12/04/2021 01:57:48 - use '-nowf' to disable wireframing completely.
12/04/2021 01:57:48 - use '-nowcr' to disable the Copy Rectangle after the
12/04/2021 01:57:48 moved window is released in the new position.
12/04/2021 01:57:48 Also see the -help entry for tuning parameters.
12/04/2021 01:57:48 You can press 3 Alt_L's (Left "Alt" key) in a row to
12/04/2021 01:57:48 repaint the screen, also see the -fixscreen option for
12/04/2021 01:57:48 periodic repaints.
12/04/2021 01:57:48 GrabServer control via XTEST.
12/04/2021 01:57:48
12/04/2021 01:57:48 Scroll Detection: -scrollcopyrect mode is in effect to
12/04/2021 01:57:48 use RECORD extension to try to detect scrolling windows
12/04/2021 01:57:48 (induced by either user keystroke or mouse input).

12/04/2021 01:57:48 If this yields undesired behavior (poor response, painting
12/04/2021 01:57:48 errors, etc) it may be disabled via: '-noscr'
12/04/2021 01:57:48 Also see the -help entry for tuning parameters.
12/04/2021 01:57:48 You can press 3 Alt_L's (Left "Alt" key) in a row to
12/04/2021 01:57:48 repaint the screen, also see the -fixscreen option for
12/04/2021 01:57:48 periodic repaints.
12/04/2021 01:57:48
12/04/2021 01:57:48 XKEYBOARD: number of keysyms per keycode 7 is greater
12/04/2021 01:57:48 than 4 and 51 keysyms are mapped above 4.
12/04/2021 01:57:48 Automatically switching to -xkb mode.
12/04/2021 01:57:48 If this makes the key mapping worse you can
12/04/2021 01:57:48 disable it with the "-noxkb" option.
12/04/2021 01:57:48 Also, remember "-remap DEAD" for accenting characters.
12/04/2021 01:57:48
12/04/2021 01:57:48 X FBPM extension not supported.
Xlib: extension "DPMS" missing on display ":0".
12/04/2021 01:57:48 X display is not capable of DPMS.
12/04/2021 01:57:48 --------------------------------------------------------
12/04/2021 01:57:48
12/04/2021 01:57:48 Default visual ID: 0x21
12/04/2021 01:57:48 Read initial data from X display into framebuffer.
12/04/2021 01:57:48 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120
12/04/2021 01:57:48
12/04/2021 01:57:48 X display :0 is 32bpp depth=24 true color
12/04/2021 01:57:48
12/04/2021 01:57:48 Listening for VNC connections on TCP port 5900
12/04/2021 01:57:48
12/04/2021 01:57:48 Xinerama is present and active (e.g. multi-head).
12/04/2021 01:57:48 Xinerama: number of sub-screens: 1
12/04/2021 01:57:48 Xinerama: no blackouts needed (only one sub-screen)
12/04/2021 01:57:48
12/04/2021 01:57:48 fb read rate: 1095 MB/sec
12/04/2021 01:57:48 fast read: reset -wait ms to: 10
12/04/2021 01:57:48 fast read: reset -defer ms to: 10
12/04/2021 01:57:48 The X server says there are 10 mouse buttons.

12/04/2021 01:57:48 screen setup finished.
12/04/2021 01:57:48

The VNC desktop is: 97d4d66b6034:0

0

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval. It should work with any VNC viewer. Try it by running:

x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

2021-04-12 01:57:50,721 Network Request: Fetching https://swscan.apple.com/content/catalogs/others/index-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
conn = connection.create_connection(
File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
raise err
File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
sock.connect(sa)
TimeoutError: [Errno 110] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
httplib_response = self._make_request(
File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
self._validate_conn(conn)
File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
conn.connect()
File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 308, in connect
conn = self._new_conn()
File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x14ddd4cf06a0>: Failed to establish a new connection: [Errno 110] Operation timed out


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
retries = retries.increment(
File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='swscan.apple.com', port=443): Max retries exceeded with url: /content/catalogs/others/index-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14ddd4cf06a0>: Failed to establish a new connection: [Errno 110] Operation timed out'))


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "fetch-macos.py", line 165, in <module>
fetchmacos()
File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "fetch-macos.py", line 146, in fetchmacos
catalog = remote.getcatalog()
File "fetch-macos.py", line 95, in getcatalog
self.catalog_data = Filesystem.fetch_plist(self.catalog_url)
File "fetch-macos.py", line 54, in fetch_plist
plist_raw = requests.get(url, headers=ClientMeta.swupdate)
File "/usr/lib/python3.8/site-packages/requests/api.py", line 76, in get
return request('get', url, params=params, **kwargs)
File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
resp = self.send(prep, **send_kwargs)
File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
r = adapter.send(request, **kwargs)
File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='swscan.apple.com', port=443): Max retries exceeded with url: /content/catalogs/others/index-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14ddd4cf06a0>: Failed to establish a new connection: [Errno 110] Operation timed out'))

```

**Comment by orangejx** [comment]
Hi there
